apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    app: delivery-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
  type: ClusterIP

