apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
      nodePort: 30006
  type: NodePort
