apiVersion: v1
kind: Service
metadata:
  name: store-service
  labels:
    app: store-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: store-service
  ports:
    - protocol: TCP
      port: 8700
      targetPort: 8700
  type: ClusterIP

