apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      name: auth-service
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nowgnas/bb:auth
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: USE_PROFILE
              value: "dev"
      restartPolicy: Always
