apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    profile: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
        profile: dev
    spec:
      containers:
        - name: order-service
          image: nowgnas/bb:order
          imagePullPolicy: Always
      restartPolicy: OnFailure

