apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8900
      targetPort: 8900
  type: ClusterIP

