apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      name: apigateway-service
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: nowgnas/bb:apigateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: USE_PROFILE
              value: "dev"
      restartPolicy: Always
