apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      name: notification-service
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: nowgnas/bb:notification
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8400
          env:
            - name: USE_PROFILE
              value: "dev"
      restartPolicy: Always
