apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8400
      targetPort: 8400
  type: ClusterIP

