apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  labels:
    app: wishlist-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: wishlist-service
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
  type: ClusterIP

