apiVersion: v1
kind: ConfigMap
metadata:
  name: product-initdb-config
  namespace: prod
data:
  initdb.sql: |
    use product;
    create table if not exists flower
    (
    flower_id          bigint auto_increment
    primary key,
    created_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    is_deleted         bit DEFAULT false          null,
    updated_at         datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    flower_name        varchar(255) null,
    language_of_flower varchar(255) null
    );
    
    create table if not exists category
    (
    category_id   bigint auto_increment
    primary key,
    created_at    datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    is_deleted    bit DEFAULT false          null,
    updated_at    datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    category_name varchar(255) null
    );
    
    create table if not exists review
    (
    review_id      bigint auto_increment
    primary key,
    created_at     datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    is_deleted     bit DEFAULT false          null,
    updated_at     datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    nickname       varchar(255) null,
    product_id     varchar(255) null,
    profile_image  varchar(255) null,
    review_content varchar(255) null,
    review_rating  double       null,
    user_id        bigint       null
    );
    
    create table if not exists review_images
    (
    review_images_id bigint auto_increment
    primary key,
    created_at       datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    is_deleted       bit DEFAULT false          null,
    updated_at       datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    review_image_url varchar(255) null,
    review_id        bigint       null,
    constraint FKn6ocagcwsaswdoh2ntvrkk5en
    foreign key (review_id) references review (review_id)
    );
    
    create table if not exists sales_resume
    (
    sales_resume_id bigint auto_increment
    primary key,
    created_at      datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    is_deleted      bit DEFAULT false          null,
    updated_at      datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    is_notified     bit          null,
    phone_number    varchar(255) null,
    product_id      varchar(255) null,
    user_id         bigint       null,
    user_name       varchar(255) null
    );
    
    create table if not exists tag
    (
    tag_id     bigint auto_increment
    primary key,
    created_at datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    is_deleted bit DEFAULT false          null,
    updated_at datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
    tag_name   varchar(255) null
    );
    
    INSERT INTO category (category_name)
    VALUES ('꽃다발'),
           ('꽃바구니'),
           ('꽃상자'),
           ('화환');
    INSERT INTO tag (tag_name)
    VALUES ('연인 선물'),
           ('친구 선물'),
           ('공기 정화'), 
           ('개업 축하'), 
           ('승진 취임'), 
           ('결혼식'), 
           ('장례식'); 
    insert into flower (language_of_flower, flower_name)
    values ('사랑', '빨간 장미'),
           ('매력', '하얀 장미'),
           ('첫사랑', '주황 장미'),
           ('행복한 사랑', '분홍 장미'),
           ('기적', '파랑 장미'),
           ('영원한사랑', '보라 장미'),
           ('변하지않는사랑', '노란 장미'),
           ('변하지않는사랑', '리시안셔스'),
           ('진실된마음', '수국'),
           ('기대', '라벤더'),
           ('평화', '국화'),
           ('일편단심', '해바라기'),
           ('감사', '카네이션'),
           ('신비', '거베라'),
           ('영원한우정', '프리지아'),
           ('애정', '튤립'),
           ('매력', '라넌큘러스'),
           ('순수한사랑', '안개꽃'),
           ('변하지않는사랑', '스타티스'),
           ('사랑스러움', '데이지'),
           ('수줍음', '작약'),
           ('행복', '델피늄');
