apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8600
      port: 8600
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: user-service
