apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
    profile: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      name: payment-service
      labels:
        app: payment-service
        profile: dev
    spec:
      containers:
        - name: payment-service
          image: nowgnas/bb:payment
          imagePullPolicy: Always
      restartPolicy: OnFailure

