apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: ClusterIP

