apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8100
      port: 8100
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: payment-service
