apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8800
  type: ClusterIP

