apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: prod
  labels:
    app: product-service
    profile: prod  # Add the profile label here
spec:
  selector:
    app: product-service
  ports:
    - name: app
      port: 8800
      targetPort: 8800
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
