apiVersion: v1
kind: Service
metadata:
  name: ngrinder-agent-service
  namespace: prod
spec:
  selector:
    app: ngrinder-agent
  ports:
    - protocol: TCP
      port: 16001
      targetPort: 16001
  # Add additional service configurations as needed
