apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      name: discovery-service
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: nowgnas/bb:discovery
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: USE_PROFILE
              value: "dev"
      restartPolicy: Always
