apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
