apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8200
      port: 8200
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: admin-service
