apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: ClusterIP

