apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: prod
  labels:
    app: store-service
    profile: prod  # Add the profile label here
spec:
  selector:
    app: store-service
  ports:
    - name: app
      port: 8700
      targetPort: 8700
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP

