apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    profile: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
        profile: dev
    spec:
      containers:
        - name: user-service
          image: nowgnas/bb:user
          imagePullPolicy: Always
      restartPolicy: OnFailure

