apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8600
      targetPort: 8600
  type: ClusterIP

