apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: prod
  labels:
    app: apigateway-service
    profile: prod  # Add the profile label here
spec:
  selector:
    app: apigateway-service
  ports:
    - name: app
      port: 8000
      targetPort: 8000
  type: ClusterIP

