apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: prod
  labels:
    app: wishlist-service
    profile: prod  # Add the profile label here
spec:
  selector:
    app: wishlist-service
  ports:
    - name: app
      port: 8500
      targetPort: 8500
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP

