apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8500
      port: 8500
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: wishlist-service
