apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      name: config-service
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: nowgnas/bb:config
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: config-env
      restartPolicy: Always
      