apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: prod
data:
  my.cnf: |
    [client]
    default-character-set = utf8mb4
    
    [mysqld]
    authentication-policy = mysql_native_password