apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    name: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30001
  type: NodePort
  