apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
      nodePort: 30000
  type: NodePort
