apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    profile: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      name: auth-service
      labels:
        app: auth-service
        profile: dev
    spec:
      containers:
        - name: auth-service
          image: nowgnas/bb:auth
          imagePullPolicy: Always
      restartPolicy: OnFailure

