apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

