apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8400
      port: 8400
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: notification-service
