apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8800
      nodePort: 30007
  type: NodePort
