apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
  labels:
    app: wishlist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      name: wishlist-service
      labels:
        app: wishlist-service
    spec:
      containers:
        - name: wishlist-service
          image: nowgnas/bb:wishlist
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
          env:
            - name: USE_PROFILE
              value: "dev"
      restartPolicy: Always
