apiVersion: v1
kind: Service
metadata:
  name: ngrinder-controller-service
  namespace: prod
spec:
  selector:
    app: ngrinder-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer