apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
    profile: dev  # Add the profile label here
spec:
  selector:
    name: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
