apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-kube
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config
              mountPath: /etc/redis-kube
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--requirepass"
            - "123456"
      volumes:
        - name: config
          configMap:
            name: redis-config