apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-initdb-config
  namespace: prod
data:
  initdb.sql: |
    use auth
    create table social_auth
    (
        oauth_id         bigint      not null
            primary key,
        created_at       datetime(6) DEFAULT CURRENT_TIMESTAMP(6) null,
        is_deleted       bit DEFAULT false         null,
        updated_at       datetime(6) DEFAULT CURRENT_TIMESTAMP(6) null,
        is_recently_out  bit         not null,
        last_logout_time datetime(6) DEFAULT CURRENT_TIMESTAMP(6) null
    );

    create table email_code
    (
        email_code varchar(255) not null
            primary key,
        created_at datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
        is_deleted bit DEFAULT false          null,
        updated_at datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
        email      varchar(255) not null
    );

    create table store_manager_auth
    (
        id               bigint auto_increment
            primary key,
        created_at       datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
        is_deleted       bit DEFAULT false          null,
        updated_at       datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
        email            varchar(255) not null,
        last_logout_time datetime(6) DEFAULT CURRENT_TIMESTAMP(6)  null,
        password         varchar(255) not null,
        status           int          null
    );