apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 9000
      port: 9000
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: auth-service
