apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
      nodePort: 30003
  type: NodePort
