apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: prod
  labels:
    app: order-service
    profile: prod  # Add the profile label here
spec:
  selector:
    app: order-service
  ports:
    - name: app
      port: 8900
      targetPort: 8900
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP

