apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      name: apigateway-service
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: nowgnas/bb:apigateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: USE_PROFILE
              value: "dev"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              value: "123456"
      restartPolicy: Always
