apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
    profile: dev  # Add the profile label here
spec:
  selector:
    app: apigateway-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

